name: marketplace_patanjali
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  fluttertoast:
  intl:
  image_picker:
  cached_network_image: 2.0.0
  permission_handler:
  razorpay_flutter: 1.1.3
  location: ^3.0.0
  geocoder: 0.2.1
  sms_autofill:
  firebase_messaging:
  photo_view: 0.9.2
  google_fonts: 1.0.0
  google_maps_flutter: ^0.5.26+4
  carousel_slider: 2.1.0
  url_launcher: 5.4.10

  flutter_local_notifications:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/LoginScreen/sendOtp.png
   - assets/images/LoginScreen/receiveOtp.png
   - assets/images/test_image.jpg
   - assets/images/videoplaceholder.png
   - assets/images/imageplaceholder.png
   - assets/images/audioplaceholder.png
   - assets/images/launch.jpg
   - assets/images/Buyer.png
   - assets/images/Seller.png
   - assets/images/banana.jpg
   - assets/images/launch.jpg
   - assets/images/maize.jpg
   - assets/images/oats.jpg
   - assets/images/adbanner.png
   - assets/appbar-logo.png
   - assets/lang/en.json
   - assets/lang/mr.json
   - assets/lang/hi.json
   - assets/lang/as.json
   - assets/lang/bn.json
   - assets/lang/gu.json
   - assets/lang/kn.json
   - assets/lang/ml.json
   - assets/lang/ne.json
   - assets/lang/or.json
   - assets/lang/pa.json
   - assets/lang/ta.json
   - assets/lang/te.json
   - assets/DashboardIcons/Aquaculture.png
   - assets/DashboardIcons/BankDetails.png
   - assets/DashboardIcons/Beekeeping.png
   - assets/DashboardIcons/Buffalo.png
   - assets/DashboardIcons/Cow.png
   - assets/DashboardIcons/Crab.png
   - assets/DashboardIcons/CropDetails.png
   - assets/DashboardIcons/EditFarmer.png
   - assets/DashboardIcons/EquipmentDetails.png
   - assets/DashboardIcons/FamilyMembers.png
   - assets/DashboardIcons/FarmerList.png
   - assets/DashboardIcons/FarmerReport.png
   - assets/DashboardIcons/FinancialDetails.png
   - assets/DashboardIcons/Fish.png
   - assets/DashboardIcons/Goat.png
   - assets/DashboardIcons/Home.png
   - assets/DashboardIcons/Income.png
   - assets/DashboardIcons/InsuranceDetails.png
   - assets/DashboardIcons/LandDetails.png
   - assets/DashboardIcons/Livestock.png
   - assets/DashboardIcons/Mandi.png
   - assets/DashboardIcons/NewFarmer.png
   - assets/DashboardIcons/OwnershipDetails.png
   - assets/DashboardIcons/PersonalInformation.png
   - assets/DashboardIcons/Poultry.png
   - assets/DashboardIcons/Prawn.png
   - assets/DashboardIcons/Sericulture.png
   - assets/DashboardIcons/Sheep.png
   - assets/DashboardIcons/SourcesOfIncome.png
   - assets/DashboardIcons/Weather.png
   - assets/DashboardIcons/Blogs.jpg
   - assets/DashboardIcons/MandiBhav.png
   - assets/DashboardIcons/Nearby.png
   - assets/DashboardIcons/NewsAndFeeds.png
   - assets/DashboardIcons/SeedQuality.png
   - assets/backgroundimg.jpg
   - assets/WeatherIcons/rain.png
   - assets/WeatherIcons/sun.png
   - assets/WeatherIcons/wind.jpg
   - assets/WeatherIcons/humidity.png
   - assets/WeatherIcons/partlycloudy.png
   - assets/WeatherIcons/thunderstorm.png
   - assets/DashboardIcons/LandMap.png
   - assets/DashboardIcons/Horticulture.png
   - assets/DashboardIcons/OccupationDetails.png
   - assets/DashboardIcons/Subsidy.png
   - assets/DashboardIcons/Weather.png
   - assets/DashboardIcons/LoanDetails.png
   - assets/DashboardIcons/IdentificationDetails.png
   - assets/haramrit.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Matura
      fonts:
        - asset: assets/fonts/maturasc.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
